<template>
  <div
    class="
    max-lg:flex
    hidden
    w-[100%]
    h-[70px]
    webkit-box-pack-start
    justify-start
    webkit-box-align-center
    items-center
    absolute
    left-0
    top-0
    z-999999999999"
  >
    <a
      class="
      max-lg:translate-x-[70px]
      max-lg:transition-all
      max-lg:duration-[0.4s]
      max-lg:delay-[0s]
      ml-auto
      pointer-events-all
      text-[14px]
      p-[30px]"
    >
      <div
        class="
        max-lg:i-carbon-overflow-menu-vertical
        font-black
        webkit-font-antialiased
        inline-block
        not-italic,
        font-variant-normal
        text-reading-auto
        leading-[1]
        font-size-inherit
        pointer-events-all"
      />
    </a>
  </div>
</template>
