<template>
  <div
    class="
    w-auto
    h-auto
    overflow-visible
    relative
    font-poppins
    lg:p-[15px] p-[0px]
    lg:before:topleft
    lg:after:topleft
    lg:after:top-auto
    lg:after:bottom-0
    lg:dark:after:bg-white
    lg:dark:before:bg-white"
  >
    <div
      class="
      h-auto
      overflow-visible
      overflow-x-hidden
      max-w-[1440px]
      mx-auto
      bg-[#1e1e28]
      bg-cover
      w-[100%]
      relative
      max-lg:rounded-[0]
      custom-shadow"
    >
      <div
        class="
        relative
        max-lg:w-100%
        flex
        flex-nowrap"
      >
        Hasan Demirtaş
      </div>
    </div>
  </div>
</template>
