<template>
  <div
    class="
    transition-all duration-[0.55s] delay-[0s]
    opacity-10"
  >
    <div
      class="
      transform-none-important
      h-auto
      overflow-visible
      w-full"
    >
      <div
        class="
        max-lg:px-[15px]
        overflow-hidden
        px-[30px]
        relative
        w-full
        mr-auto
        ml-auto"
      >
        Footer
      </div>
    </div>
  </div>
</template>
